apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - patch: |
      apiVersion: v1
      kind: Kustomization
      metadata:
        name: flux-system
      spec:
        decryption:
          provider: sops
          secretRef:
            name: sops-age
    target:
      kind: Kustomization
      name: flux-system
