apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: factorio
  namespace: factorio
spec:
  selector:
    matchLabels:
      app: factorio
  serviceName: factorio
  replicas: 1
  template:
    metadata:
      labels:
        app: factorio
    spec:
      securityContext:
        fsGroup: 845
      initContainers:
        - name: copy-config
          image: busybox
          command:
            [
              "sh",
              "-c",
              "cp /config/* /factorio/config/ && cp /secret/* /factorio/config/ && chown -R 845:845 /factorio/config",
            ]
          volumeMounts:
            - name: factorio-config
              mountPath: /config
            - name: factorio-secret
              mountPath: /secret
            - name: factorio
              mountPath: /factorio
      containers:
        - name: factorio
          image: factoriotools/factorio:2.0.24
          env:
            - name: PORT
              value: "30197"
          ports:
            - containerPort: 27015
              name: "rcon"
              protocol: TCP
            - containerPort: 30197
              name: "game"
              protocol: UDP
          volumeMounts:
            - name: factorio
              mountPath: /factorio

      volumes:
        - name: factorio-config
          configMap:
            name: factorio-config
        - name: factorio-secret
          secret:
            secretName: factorio

  volumeClaimTemplates:
    - metadata:
        name: factorio
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: factorio
  namespace: factorio
  labels:
    app: factorio
spec:
  type: NodePort
  ports:
    - port: 30197
      nodePort: 30197
      protocol: UDP
      name: "game"
      targetPort: "game"
  selector:
    app: factorio
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: factorio-config
  namespace: factorio
data:
  "server-adminlist.json": |
    [
    "nepoxx"
    ]
