---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: overseerr
  namespace: overseerr
  labels:
    type: local
spec:
  interval: 24h
  url: https://k8s-at-home.com/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: overseerr
spec:
  interval: 1h
  chart:
    spec:
      chart: overseerr
      version: "5.4.*"
      sourceRef:
        kind: HelmRepository
        name: overseerr
        namespace: overseerr
      interval: 12h
  values:
    image:
      tag: 1.33.2
    env:
      TZ: "America/New York"

    persistence:
      config:
        enabled: true
        mountPath: /app/config
        accessMode: "ReadWriteOnce"
        size: "1Gi"

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/target: ${ddns_target}
        hosts:
          - host: overseerr.${base_domain}
            paths:
              - path: "/"
        tls:
          - hosts:
              - overseerr.${base_domain}
            secretName: overseerr-tls
