apiVersion: v1
kind: Secret
metadata:
    name: valheim
    namespace: valheim
stringData:
    server_password: ENC[AES256_GCM,data:QzXf+8SB8X9Vew==,iv:Dt8orAQRjpliqCj5YaWxTWXnRbaD9vRp9T2PNaq8/4k=,tag:kxUq26gvxvk8gFT06V0DUA==,type:str]
sops:
    age:
        - recipient: age1m986kl5ewqh3e84cj8lwav4uty7pyyv0zxa9psr6nxnnwndmxgdqqmlfc4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBER0w1VzhBL2FyRXFkbi9D
            NTBsZVFkZS81Mi9ueEt4QlN5NTREcmxsalZBCm5pRTVNZGlrZmVEeis4Sy9hbTZp
            a0ZpUnhIZDVnVDhzY2QwRXhCRGhOeG8KLS0tIG5rUEJKLzhKckVGUTlkQk1STTMr
            TTR0aHlKRC9ENzNxVVpnWkVDcElId2MKyGqbpQ6kdSJx4HIEaA17SmKIRhoJ7EQa
            Wp0XuhqLLK9cOnLiicOqEPqtYVllFdUkggiD5XpveJoKIXiPN1b50Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T16:42:39Z"
    mac: ENC[AES256_GCM,data:0Y0AZNRk/nRTeR0cJUJMMiADfJhj52gRzsyvns/B469ZHNPcLEcGyGtrjBHL49xLfn6dCFTMh2FrUaZ9blP8u9hRNSRv9CMYj9bQiSfr5BnsNhhh4rkoTk0aOBzeZ1BZxjSSuOnJDQbKC7nN5FTgEptQ9CdeDMh0bSnEv88lSOc=,iv:hUBDID3QX+/0W+Dc86+6Mz1ZMCfDTc0kRxca/CdvMRE=,tag:0hHltD3mRWv0l2nE6tArBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
