apiVersion: v1
kind: Service
metadata:
  name: valheim
  namespace: valheim
spec:
  type: NodePort
  ports:
    - port: 2456
      nodePort: 32456
      protocol: UDP
      name: "valheim1"
      targetPort: "valheim1"
    - port: 2457
      nodePort: 32457
      protocol: UDP
      name: "valheim2"
      targetPort: "valheim2"
    - port: 2458
      nodePort: 32458
      protocol: UDP
      name: "valheim3"
      targetPort: "valheim3"
  selector:
    app: valheim
