apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  replicas: 1
  serviceName: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio
          args:
            - server
            - /data
          env:
            - name: MINIO_ROOT_USER
              value: "nepoxx"
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: root_password
            - name: MINIO_DOMAIN
              value: "minio.${base_domain}"
            - name: MINIO_SERVER_URL
              value: "https://minio.${base_domain}"
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /data
              name: minio-data
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 20
      volumes:
        - name: minio-data
          hostPath:
            path: /media/external2tb/k3s/minio

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
  type: ClusterIP
