apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: paperless
    namespace: paperless
    labels:
        type: local
spec:
    interval: 24h
    url: https://charts.gabe565.com
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m986kl5ewqh3e84cj8lwav4uty7pyyv0zxa9psr6nxnnwndmxgdqqmlfc4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WE9UYjVnTjJXT09nQzZ2
            SlhiMlU1RlZFK0xRMkpLQXJHUlZTbGRpQnhjClRzYVYyWW5hWXpXOVFYK2pTTlM0
            NUltUDB2UFFZSllEc2pMT2lJQjlyQ0EKLS0tIEVJQTI1MkRMWHkrV2FQMVA0VzBv
            RDFBZ2ZzMEhEY3NLWlUzUnhLL2F4V3MKA9S08CLUSOHHka1SSuVhP7xjzEL6bDBY
            s+lz64IyAJ5dMzd1GGk5KMXFJfFpUqqahypI1GkmU6CKv7TUJXAEkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-07T02:02:32Z"
    mac: ENC[AES256_GCM,data:f4lnPGLmyCKHQk6JI9o6xrUPkieBakP7z3woLh8rC4Ia+zH/fdIkvKyVq7Eg2+y3ROjDhyK0TtGoUCCv0uxWciKfUaWbRIbBPTtsCnjq7n27uAYuAFd06shGETdJzBLhlZFzwcOjMBkfzHVgq1vCXzTUMj2djIzfQaCEBKaJLtQ=,iv:fwjiQSs261mA3XD4HlT2RRPMIGHE4oA0JeXeRXl2758=,tag:PSeYjHMLhVlbL7mxXEkJEQ==,type:str]
    pgp: []
    encrypted_regex: PAPERLESS_SECRET_KEY
    version: 3.8.1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: paperless
    namespace: paperless
spec:
    interval: 1h
    chart:
        spec:
            chart: paperless-ngx
            version: 0.*
            sourceRef:
                kind: HelmRepository
                name: paperless
                namespace: paperless
            interval: 12h
    values:
        env:
            PAPERLESS_URL: https://paperless.${base_domain}
            PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:kBUyoZIzio1vhuF98dM1CRJ575HKZzJR+ah/ZBAYJz2zGE5BNJTpXrR+ieJ1rx8r3sks0RtjMVlPgCBCg3zmxaA799CrNWJoVduUGPQTrTB0Ccd4kw9edI9GjcnXm35dPa/6arFoeR165SNKILKWThOXil7+7xZRL4xzlT2J8LE=,iv:jw5+I+8bpBooRQhbJ7zf02sa7XWqGukX8jWKwWC0aUU=,tag:WG0qqBQb+2jQLyzTOJtW/Q==,type:str]
            PAPERLESS_TIME_ZONE: America/Toronto
        persistence:
            data:
                enabled: true
                mountPath: /media/external2tb/k3s/paperless/data
                accessMode: ReadWriteOnce
                size: 5Gi
            media:
                enabled: true
                mountPath: /media/external2tb/k3s/paperless/media
                accessMode: ReadWriteOnce
                size: 5Gi
            export:
                enabled: true
                mountPath: /media/external2tb/k3s/paperless/export
                accessMode: ReadWriteOnce
                size: 5Gi
            consume:
                enabled: true
                mountPath: /media/external2tb/k3s/paperless/consume
                accessMode: ReadWriteOnce
                size: 20Gi
        ingress:
            main:
                enabled: true
                ingressClassName: traefik
                annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                    external-dns.alpha.kubernetes.io/target: ${ddns_target}
                hosts:
                    - host: paperless.${base_domain}
                      paths:
                        - path: /
                tls:
                    - hosts:
                        - paperless.${base_domain}
                      secretName: paperless-tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m986kl5ewqh3e84cj8lwav4uty7pyyv0zxa9psr6nxnnwndmxgdqqmlfc4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WE9UYjVnTjJXT09nQzZ2
            SlhiMlU1RlZFK0xRMkpLQXJHUlZTbGRpQnhjClRzYVYyWW5hWXpXOVFYK2pTTlM0
            NUltUDB2UFFZSllEc2pMT2lJQjlyQ0EKLS0tIEVJQTI1MkRMWHkrV2FQMVA0VzBv
            RDFBZ2ZzMEhEY3NLWlUzUnhLL2F4V3MKA9S08CLUSOHHka1SSuVhP7xjzEL6bDBY
            s+lz64IyAJ5dMzd1GGk5KMXFJfFpUqqahypI1GkmU6CKv7TUJXAEkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-07T02:02:32Z"
    mac: ENC[AES256_GCM,data:f4lnPGLmyCKHQk6JI9o6xrUPkieBakP7z3woLh8rC4Ia+zH/fdIkvKyVq7Eg2+y3ROjDhyK0TtGoUCCv0uxWciKfUaWbRIbBPTtsCnjq7n27uAYuAFd06shGETdJzBLhlZFzwcOjMBkfzHVgq1vCXzTUMj2djIzfQaCEBKaJLtQ=,iv:fwjiQSs261mA3XD4HlT2RRPMIGHE4oA0JeXeRXl2758=,tag:PSeYjHMLhVlbL7mxXEkJEQ==,type:str]
    pgp: []
    encrypted_regex: PAPERLESS_SECRET_KEY
    version: 3.8.1
