---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: paperless
  namespace: paperless
  labels:
    type: local
spec:
  interval: 24h
  url: https://charts.gabe565.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 1h
  chart:
    spec:
      chart: paperless-ngx
      version: "0.*"
      sourceRef:
        kind: HelmRepository
        name: paperless
        namespace: paperless
      interval: 12h
  values:
    persistence:
      data:
        enabled: true
        retain: true
        mountPath: /media/external2tb/k3s/paperless/data
        accessMode: ReadWriteOnce
      media:
        enabled: true
        retain: true
        mountPath: /media/external2tb/k3s/paperless/media
        accessMode: ReadWriteOnce
      export:
        enabled: true
        retain: true
        mountPath: /media/external2tb/k3s/paperless/export
        accessMode: ReadWriteOnce
      consume:
        enabled: true
        retain: true
        mountPath: /media/external2tb/k3s/paperless/consume
        accessMode: ReadWriteOnce
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/target: ${ddns_target}
        hosts:
          - host: paperless.${base_domain}
            paths:
              - path: "/"
        tls:
          - hosts:
              - paperless.${base_domain}
            secretName: paperless-tls
