# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
#   labels:
#     app: nginx
# spec:
#   ports:
#   - port: 80
#     name: web
#   selector:
#     app: nginx
#   type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rflood
  namespace: rflood
spec:
  selector:
    matchLabels:
      app: rflood
  template:
    metadata:
      labels:
        app: rflood
    spec:
      containers:
        - name: rflood
          image: cr.hotio.dev/hotio/rflood
          ports:
            - containerPort: 3000
              name: web
          volumeMounts:
            - name: config
              mountPath: /config
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn-single"
        resources:
          requests:
            storage: 1Gi
# services:
#   rflood:
#     container_name: rflood
#     image: cr.hotio.dev/hotio/rflood
#     ports:
#       - "3000:3000"
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - UMASK=002
#       - TZ=Etc/UTC
#       - FLOOD_AUTH=false
#     volumes:
#       - /<host_folder_config>:/config
