---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 24h
  url: oci://code.forgejo.org/forgejo-helm/forgejo
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 1h
  chart:
    spec:
      chart: forgejo
      version: "16.0.*"
      sourceRef:
        kind: OCIRepository
        name: forgejo
        namespace: forgejo
      interval: 12h
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: ${ddns_target}
      hosts:
        - host: forgejo.${base_domain}
          paths:
            - path: "/"
      tls:
        - hosts:
            - forgejo.${base_domain}
          secretName: forgejo-tls
    # image:
    #   tag: 1.33.2
    # env:
    #   TZ: "America/New York"

    # persistence:
    #   config:
    #     enabled: true
    #     mountPath: /app/config
    #     accessMode: "ReadWriteOnce"
    #     size: "1Gi"

    # ingress:
    #   main:
    #     enabled: true
    #     ingressClassName: traefik
    #     annotations:
    #       cert-manager.io/cluster-issuer: letsencrypt
    #       external-dns.alpha.kubernetes.io/target: ${ddns_target}
    #     hosts:
    #       - host: overseerr.${base_domain}
    #         paths:
    #           - path: "/"
    #     tls:
    #       - hosts:
    #           - overseerr.${base_domain}
    #         secretName: overseerr-tls
