---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transmission
  namespace: transmission
spec:
  serviceName: transmission
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:latest
          ports:
            - containerPort: 9091
            - containerPort: 51413
            - containerPort: 51413
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          env:
            - name: user
              value: nepoxx
            - name: pass
              value: "1234"
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn-single"
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: downloads
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn-single"
        resources:
          requests:
            storage: 50Gi
