apiVersion: v1
kind: Secret
metadata:
    name: immich-email
stringData:
    user: ENC[AES256_GCM,data:fRO3GnJUi5Dqs8jvoK+qhRlVt6eld7JB,iv:is336mgi3qc9F8i2lTjgaiJ3p9WCxaGK+7ELY7TODQA=,tag:W/QFCAccfXWW2xZ31KiQ5A==,type:str]
    password: ENC[AES256_GCM,data:VXhPcVmvJvmapSFqi+PT6g==,iv:dhvft+C6kYloP+auETrWu0Vz9dN8AFtXxEuu/V98gzQ=,tag:RJazvgTrt9tzWkr3p/Vo8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNLzJoTFF5NWl4K3JwUktP
            bU0weTEvMGV0cnc0MUI3ZnloQXREVnJINkdnCnl0YW84QnRhcnR4Nk9zNjNQQ0x5
            MTh5dkxOVVlTMXQ3dU5IeTcxTGRUZDQKLS0tIGdXdm5oMjhKOFVKSTVlYUp1b1Uz
            TFF2VnhrallXeTVIa3NMYzFaL2pXSkUKcVzpSJ2GFREXRu78cncI8p+prMglSwck
            bUDafW9yETyihFGxr0/aBpvZ0vhqbnk9Sz2PgTURcVgFRnl24rV1+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m986kl5ewqh3e84cj8lwav4uty7pyyv0zxa9psr6nxnnwndmxgdqqmlfc4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T23:40:06Z"
    mac: ENC[AES256_GCM,data:lqH9USQN+9yDUJQEp1x4XdnQaW9viLSmow4ixH4aSRE092Mai2bh8bc+ztMJu94WbfcY/NJoVsIdjiiIWyup1kJmcn3NdsijUW8/OFSWSZRLyIqBgeNhYKtPVQn4Bsq5eO6CQUdmXUeFo0uz2cE+22Xg41OYqAkPyPHkWRNaw2I=,iv:ahI7sdlTLgSXB8tbn5me9EfFKVGUFyS1xWSCFC/Y9Ic=,tag:MeFMv9FMB7W/AyE4mCEKWw==,type:str]
    version: 3.13.3
