apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres
stringData:
    password: ENC[AES256_GCM,data:FnKyxI7C68b4Mfe7ZeBcRyvgRh7IpGKUaqvMVyqtl5qRNqKbta7EYeqDcckox89x,iv:F2hVOIyWhvfi27mV8ZMolrBg/vLuySltx1NRFhSUKpc=,tag:U/9oltciYuvRIIA0LrBpXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK0tLREh3YUFEbGRPNzkx
            SkNuYmhRTk5pd3FZUmxoUG5UMHBBSDJOTmhrCjUzTWU3UW1rZmhQZ3RUazNhbUVG
            T1M0WjdRSTROSGs1S2VTWTlDZ1g1Y2sKLS0tIEFoaTRiNlB3NmlLbGt0L1pSOFVK
            aW9zTm5tcGhzTXVpOVRpLysxbWc2SlkKxmye5k1JRYkEzROHyjwOaiFrjis4G4WC
            4jv2L3qbngrvrc3zyYw02NpbE4HiCEYBOaLICnz/RZIr9v0VITgntg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m986kl5ewqh3e84cj8lwav4uty7pyyv0zxa9psr6nxnnwndmxgdqqmlfc4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T22:40:46Z"
    mac: ENC[AES256_GCM,data:UtcK7PE68Uq8g1LiuCIcTvaQ8M/bcdrFroeproqulwBDRfcZd3Ve/HShS2xqGbauFeaqEScIknO6YAXdVO3F5SKOOazW5rNjm5OY6MG33e5F6tGUsTZdoBWyabXVUKTp3YJvukj1l8MlrQ0oj/Tooq9KY8iB234ehfy8/Kktcqo=,iv:TiR4FakUOcdSvConxCsp2MNSWsWRWK8iI/2MXLFU9j0=,tag:nvLzl26/SA7jiblDiyoKgw==,type:str]
    version: 3.13.3
