apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pv
  namespace: immich
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /media/external2tb/k3s/immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pv-claim
  namespace: immich
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
